# Generated by Django 2.2.5 on 2019-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('siren', 'сирена'), ('loudspeaker', 'громкоговоритель')], max_length=1, verbose_name='Устройство')),
                ('address', models.TextField(max_length=150, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('radius', models.BigIntegerField(verbose_name='Радиус зоны звукопокрытия')),
            ],
        ),
    ]
