# Generated by Django 2.2.5 on 2019-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodev', '0002_auto_20190925_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationdevice',
            name='device_type',
            field=models.CharField(choices=[('siren', 'сирена'), ('loudspeaker', 'громкоговоритель')], max_length=50, verbose_name='Устройство'),
        ),
    ]
